logging:
  config: classpath:logback.xml
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.102.119.147:3306/tepth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: tepth_666
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

url:
  login: http://127.0.0.1:8081/common/login
  fault:
    search: http://127.0.0.1:8081/driver/searchFault
    add: http://127.0.0.1:8081/driver/addFault