logging:
  config: classpath:logback.xml
server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://47.102.119.147:3306/tepth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: tepth_666
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: dispatch
  cloud:
    client:
      ipAddress: 168.192.0.108

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

url:
  login: http://127.0.0.1:8081/common/login
  fault:
    search: http://127.0.0.1:8081/driver/searchFault
    add: http://127.0.0.1:8081/driver/addFault

# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.102.119.147:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

